### ISSUE TITLE
Unable to create/edit fields for an Assets volume when this plugin is installed

### ISSUE THREAD

**Issue by croxton** [craftcms/google-cloud#1]
The 'Field layout' tab for all volumes is entirely blank when this plugin is installed (whether the volume is a Google Cloud Storage bucket or not). Any existing asset fields remain editable.

Craft 3 RC2
PHP 7.1.12
MySQL 5.7.20
Google Cloud Storage 1.0.3

**Comment by brandonkelly** [comment]
Thanks!
