### ISSUE TITLE
Can we make the auth file fetchable by an environment variable as well?

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/google-cloud#12]
Hi,

Is it possible to also allow the contents of the auth file to be loaded from and environment variable?
.env allows this json content like this: `GOOGLE_AUTH='{}`

Since we're running on heroku, and we don't want the auth credentials to be in the repo, we don't want to use the regular way of setting GOOGLE_APPLICATION_CREDENTIALS or saving the information to the database/project config.

**Comment by andris-sevcenko** [comment]
I just pushed this for the next release due next week.

**Comment by andris-sevcenko** [comment]
1.4.0 is out with now with this feature. Keep in mind you'll have to properly escape newline characters in the RSA key.
