### ISSUE TITLE
File deletion fails quietly when its blocked due to bucket retention policy

### ISSUE THREAD

**Issue by piotrpog** [craftcms/google-cloud#13]
When I try to remove the file which cannot be removed due to bucket retention policy, nothing shows up in craft control panel - files just don't get deleted. I needed to check in the "network" tab of browser console to see what was happening.

**Comment by andris-sevcenko** [comment]
All fixed up for the next week's release!

**Comment by andris-sevcenko** [comment]
1.4.0 is out with now with this fix!
