### ISSUE TITLE
Folders deleted or moved in Assets are not deleted in Google Cloud

### ISSUE THREAD

**Issue by croxton** [craftcms/google-cloud#2]
If a folder is _deleted_ in Assets, it remains in place in Google Cloud Storage (any files/images inside the deleted folder are however deleted in Google Cloud too).

If a folder is _moved_ to a new location in Assets, the directory remains in the original location in Google Cloud Storage, but the files inside are moved. The directory that was moved is created in the new location and contains the files/images that were moved (as expected). So you end up with two folders, the original (empty) and the copy in the new location (with files inside). 

Re-indexing brings back these 'ghost' folders.

Craft Pro 3.0.0-RC15
PHP 7.1.12
MySQL 5.7.20
Google Cloud Storage 1.0.5

**Comment by andris-sevcenko** [comment]
You'll want to be updated to at least craftcms/cms@2df0a8b, too.

**Comment by croxton** [comment]
Awesome thank you!
