### ISSUE TITLE
bucketSelectionMode not working/documented

### ISSUE THREAD

**Issue by hohler** [craftcms/google-cloud#24]
### Description
I would like to use environment variables for the `bucket` instead of the list (which requires the service account to have list-permissions). I found this setting `bucketSelectionMode: choose` in the volume config file and in https://github.com/craftcms/google-cloud/blob/master/src/Volume.php#L81. However, it does not seem to make any difference for the volume configuration.

### Steps to reproduce

1. Create a Google Cloud Storage Volume
2. Change `bucketSelectionMode` to `manual` in the volume .yaml file
3. Update the `project.yaml` timestamp.
4. Apply the project config
5. Try to edit the created Volume - the bucket is still a dropdown / selection.

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Google Cloud Storage 1.4.0

**Comment by andris-sevcenko** [comment]
Just released the 1.4.1 version of this plugin that allows this!
