### ISSUE TITLE
Dependency prevents other plugins being installed 

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/google-cloud#3]
The hard dependency on `"superbalist/flysystem-google-storage": "5.0.0"` prevents use of any other plugins using recent versions of the Google PHP SDKs due to dependency conflicts.

Consider updating to "^7.0.0". I've just tested it out and it all seems to work fine with no other alterations required.

:ok_hand:

**Comment by andris-sevcenko** [comment]
Your wish is my command. (366cdbdaade292e3737b1aba47b1395ecdc1a714)
