### ISSUE TITLE
Plugin Broken:  Volume.php does not implement a validate method

### ISSUE THREAD

**Issue by Yugloocamai** [craftcms/google-cloud#4]
I'm not sure how this plugin can work with Craft without a validate method.  It does not work for me.  When Craft3 calls `saveVolume`, it calls the validation method which will always return null since the method is not implemented.  Perhaps Craft3 added that step recently?
```
        if ($runValidation && !$volume->validate()) {
            Craft::info('Volume not saved due to validation error.', __METHOD__);
            return false;
        }
```

**Comment by andris-sevcenko** [comment]
The method is implemented in `yii\base\Model`, from which the `craft\googlecloud\Volume` inherits it.

**Comment by Yugloocamai** [comment]
I can see that now.  I assumed validate() wasn't implemented because it was failing silently.  It turns out that the issue is that I'm trying to switch a storage volume from Amazon S3 to Google Cloud.  It might be worth having some messaging around that.  That it will fail validation because they have different required fields...

**Comment by Yugloocamai** [comment]
It looks like the validation error is actually ` Bucket cannot be blank.`, but the toast message on the front end is just `Couldn’t save volume.`  I think the real issue here might just be messaging.

**Comment by andris-sevcenko** [comment]
Ah, nice find! Fixed for next release.
