### ISSUE TITLE
Unable to upload a file

### ISSUE THREAD

**Issue by JulieVelghe** [craftcms/google-cloud#40]
### Description
Hi all,
we've made a website for a client, where we now need to be able to upload files to a google cloud storage via a form.
My media system for audio files is setup like this:
![image](https://github.com/user-attachments/assets/777944ef-8282-4276-bd57-338bd01d5226)
I am using variables from my env file:

GOOGLE_APPLICATION_CREDENTIALS="D:/Julie/Repos/Ritcs/erasmushogeschool-brussel-fb3422db4ecf.json"
GOOGLE_CLOUD_PROJECT_ID="erasmushogeschool-brussel"
GOOGLE_CLOUD_URL="https://storage.googleapis.com/ritcs-folio"
When I submit my form with an audio file, I get a filesystem error (see attached pdf)
[Filesystem Error – craft_errors_FsException.pdf](https://github.com/user-attachments/files/16363345/Filesystem.Error.craft_errors_FsException.pdf)
I've checked on Google Cloud, and our service account has the role 'Storage Admin', which should have enough rights to everything. 

### Steps to reproduce

1. setup a local craft site. 
2. setup a google cloud storage
3. setup a file system that connects to the cloud storage
4. upload a file via the cms, or alternativly, setup a formie form with a file upload and test that way.

### Additional info

- Craft version: 4.10.2
- PHP version: 8.1.0
- Database driver & version:
- Plugins & versions: 
Formie | 2.1.19
Google cloud storage | 2.2.0

**Comment by angrybrad** [comment]
Context here: https://github.com/craftcms/cms/discussions/15284#discussioncomment-10137597

If you remove Craft/PHP from the equation and try to connect to Google Cloud storage using the same credentials in your `D:/Julie/Repos/Ritcs/erasmushogeschool-brussel-fb3422db4ecf.json` file [via the CLI](https://cloud.google.com/sdk/gcloud/reference/storage), are you able to connect, upload, or delete files from the CLI in that scenario?

**Comment by JulieVelghe** [comment]
@angrybrad I haven't tried via the cli yet. I did try to remove Craft from the equation by making a simple php script that tries to upload a file using the same json credential file, and that seems to work.
![image](https://github.com/user-attachments/assets/4e5abf06-42c7-4a31-8405-342785829676)
![image](https://github.com/user-attachments/assets/d0f90af2-edc3-4a77-88b1-e8b1d13f1b1e)

the setup for this test was quite simple:
![image](https://github.com/user-attachments/assets/45df7222-1cc8-4ccc-a92c-094756290ebb)
And below the script I used:

```
<?php

require 'vendor/autoload.php';
use Google\Cloud\Storage\StorageClient;

// Authenticating with keyfile data.
$storageClient = new StorageClient([
    'keyFilePath' => __DIR__ . '/data/erasmushogeschool-brussel-fb3422db4ecf.json',
]);
$bucket = $storageClient->bucket('ritcs-folio');

if ($bucket->exists()) {
        echo 'Bucket exists!';
}else{
    echo 'Bucket not found';
}

$buckets = $storageClient->buckets();

foreach ($buckets as $bucket) {
    echo $bucket->name() . PHP_EOL;
}

// Upload a file to the bucket.

$sPath = __DIR__ . '/data/PaulineNeverSaidIWasAnAngel.mp3';
$objectName = "audio/PaulineNeverSaidIWasAnAngel.mp3";

$options = [
    'name' => $objectName
];

try {
    $bucket -> upload(
        fopen($sPath, 'r'),
        $options
    );
    echo "File was successfully uploaded/written to Google Cloud Storage.";
} catch (Exception $e) {
    echo "Could not upload/write the file to Google Storage. Reason: {$e->getMessage()}";
}

?>
```

**Comment by JulieVelghe** [comment]
@angrybrad I've just tried to use the cli. I have been able to use the json key file and upload the audio file:
![image](https://github.com/user-attachments/assets/d61589dd-e5b7-40a7-9751-9b88579354e7)
![image](https://github.com/user-attachments/assets/504e2e9c-449a-4626-8099-039d776df6d4)
What I did get however on the cli, when I first tried to list the projects, was an error telling me I needed to enable the Cloud Resource Manager api.
Is this api also needed for the craft plugin? Or are there any other api's that perhaps need to be enabled?

**Comment by croxton** [comment]
@JulieVelghe this guide is a little old now but may help with permissions: https://gist.github.com/croxton/77c610289b631998283efa637f66b9f3

In particular note that bucket access must be set to fine-grained (per-object) NOT  uniform (per bucket) to work properly with the Craft Google Cloud plugin.

**Comment by JulieVelghe** [comment]
@croxton yes, that fine-grained access did fix it.

**Comment by angrybrad** [comment]
Thanks, all - I've added more details to the setup instructions https://github.com/craftcms/google-cloud/commit/f4e29a2e993df2a88d94fe24c2942eb47578b893
