### ISSUE TITLE
Changing focal point has no effect due to cache

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/google-cloud#9]
Every image automatically gets a parameter appended, like this: `?mtime=20190819123809`

When I update the Focal point of an image (or make other changes with the Image editor), they have no effect, because the image is still cached with the 'mtime' parameter that doesn't get updated. If I remove the 'mtime' parameter to see the original transformed image, then the changes are visible.

Is this a Google Cloud issue or craft/plugin related?

**Comment by thijskaspers** [comment]
Seems related to https://github.com/craftcms/cms/issues/3685

**Comment by andris-sevcenko** [comment]
Closing this in favor of craftcms/cms#3685
